package:
  name: scpw
  version: {{ GIT_DESCRIBE_TAG }}

source:
  path: ..

build:
  script: "pip install . --no-deps --ignore-installed --no-cache-dir -vvv"
  number: 1

  entry_points:
    - scpw = scpw.scpw:main

requirements:
  build:
    - python
    - pip

  run:
    - python 3.7
    - numpy

test:
  imports:
    - scpw

  requires:
    - pytest
  run:
    - pytest
about:
  home: https://github.com/lorenzocerrone/smallest-conda-package-west
  license: MIT